name: Deploy Vite to GitHub Pages

on:
  push:
    branches:
      - main # Adjust to your source branch (e.g., main or master)

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use a recent Node.js version (Vite recommends 18 or 20)
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Vite Project
        run: npm run build
        env:
          BASE_PATH: '/<repository-name>/' # Replace with your repo name or '/' for root domain

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist # Vite's build output directory

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4